wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.26
    framework: torch
    is_jupyter_run: false
    python_version: 3.8.1
batch_size:
  desc: null
  value: 46
channels_1:
  desc: null
  value: 221
channels_2:
  desc: null
  value: 92
channels_3:
  desc: null
  value: 59
dropout:
  desc: null
  value: 0.28394864931081076
epochs:
  desc: null
  value: 198
input_channels:
  desc: null
  value: 32
input_seq_len:
  desc: null
  value: 100
kernel_1:
  desc: null
  value: 31
kernel_2:
  desc: null
  value: 11
kernel_3:
  desc: null
  value: 8
lin_features_1:
  desc: null
  value: 194
lin_features_2:
  desc: null
  value: 93
lin_features_3:
  desc: null
  value: 22
mapping_dim:
  desc: null
  value: 4
used_pct:
  desc: null
  value: 0.5
