wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.26
    framework: torch
    is_jupyter_run: false
    python_version: 3.8.1
batch_size:
  desc: null
  value: 54
channels_1:
  desc: null
  value: 126
channels_2:
  desc: null
  value: 38
channels_3:
  desc: null
  value: 60
dropout:
  desc: null
  value: 0.3677828822829836
epochs:
  desc: null
  value: 127
input_channels:
  desc: null
  value: 32
input_seq_len:
  desc: null
  value: 100
kernel_1:
  desc: null
  value: 8
kernel_2:
  desc: null
  value: 15
kernel_3:
  desc: null
  value: 7
lin_features_1:
  desc: null
  value: 95
lin_features_2:
  desc: null
  value: 81
lin_features_3:
  desc: null
  value: 37
mapping_dim:
  desc: null
  value: 4
used_pct:
  desc: null
  value: 0.1
