wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.26
    framework: torch
    is_jupyter_run: false
    python_version: 3.8.1
batch_size:
  desc: null
  value: 32
channels_1:
  desc: null
  value: 128
channels_2:
  desc: null
  value: 64
channels_3:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.4
epochs:
  desc: null
  value: 100
input_channels:
  desc: null
  value: 32
input_seq_len:
  desc: null
  value: 100
kernel_1:
  desc: null
  value: 16
kernel_2:
  desc: null
  value: 8
kernel_3:
  desc: null
  value: 4
lin_features_1:
  desc: null
  value: 128
lin_features_2:
  desc: null
  value: 64
lin_features_3:
  desc: null
  value: 32
mapping_dim:
  desc: null
  value: 2
used_pct:
  desc: null
  value: 0.1
