wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.26
    framework: torch
    is_jupyter_run: false
    python_version: 3.8.1
batch_size:
  desc: null
  value: 52
channels_1:
  desc: null
  value: 182
channels_2:
  desc: null
  value: 62
channels_3:
  desc: null
  value: 43
dropout:
  desc: null
  value: 0.22513830169743446
epochs:
  desc: null
  value: 57
input_channels:
  desc: null
  value: 32
input_seq_len:
  desc: null
  value: 100
kernel_1:
  desc: null
  value: 9
kernel_2:
  desc: null
  value: 13
kernel_3:
  desc: null
  value: 8
lin_features_1:
  desc: null
  value: 252
lin_features_2:
  desc: null
  value: 63
lin_features_3:
  desc: null
  value: 22
mapping_dim:
  desc: null
  value: 2
used_pct:
  desc: null
  value: 0.1
