wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.26
    framework: torch
    is_jupyter_run: false
    python_version: 3.8.1
batch_size:
  desc: null
  value: 41
channels_1:
  desc: null
  value: 194
channels_2:
  desc: null
  value: 93
channels_3:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.6324499638683251
epochs:
  desc: null
  value: 96
input_channels:
  desc: null
  value: 32
input_seq_len:
  desc: null
  value: 100
kernel_1:
  desc: null
  value: 17
kernel_2:
  desc: null
  value: 13
kernel_3:
  desc: null
  value: 6
lin_features_1:
  desc: null
  value: 250
lin_features_2:
  desc: null
  value: 116
lin_features_3:
  desc: null
  value: 50
mapping_dim:
  desc: null
  value: 4
used_pct:
  desc: null
  value: 0.1
